version: '3.3'

services:
  postgres-dev:
      image: postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: dev
      ports:
        - "5432:5432"
      restart: unless-stopped